name: Python GitActions
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: install python packages
      run:
        python -m pip install --upgrade pip
        pip install pandas
        pip install requests
        pip install beautifulsoup4
        pip install google-cloud-storage
        pip install mysql-connector-python
        pip install --upgrade google-api-python-client
    - name: Start Google Cloud SQL Proxy
      shell: bash
      run: 
        curl -o cloud-sql-proxy https://storage.googleapis.com/cloud-sql-connectors/cloud-sql-proxy/v2.3.0/cloud-sql-proxy.linux.amd64
        chmod +x cloud-sql-proxy      
        cloud-sql-proxy
        ./cloud_sql_proxy -instances=dataops-383600:us-central1:root -dir=cloudsql
        sleep 3
          isready=0
          for i in {1..10}; do
            echo "Wait for connections to be ready ... $i/10"
            (${{ github.action_path }}/wait-for-it.sh --quiet --timeout=3 --host=127.0.0.1 --port=${{ inputs.port }} || exit $?) && true # escape bash's pipefail
            isready=$?
            if [[ $isready -eq 0 ]]; then
              break
            fi
            sleep 2
          done
          if [[ $isready -ne 0 ]]; then
            exit $isready 
          fi
    - name: execute py script
      run: python scraping_script.py
    - uses: stefanzweifel/git-auto-commit-action@v4
