name: Python GitActions
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: install python packages
      run:
        python -m pip install --upgrade pip
        pip install pandas
        pip install requests
        pip install beautifulsoup4
        pip install google-cloud-storage
        pip install mysql-connector-python
        pip install --upgrade google-api-python-client
        pip install oauth2client
    - name: execute py script
      run: python scraping_script.py
    - uses: stefanzweifel/git-auto-commit-action@v4
