name: Python GitActions
on: push

jobs:
  build-linux:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v3
      with:
        python-version: '3.11'
    - name: install python packages
      run:
        python -m pip install --upgrade pip
        pip install pandas
        pip install requests
        pip install beautifulsoup4
        pip install google-cloud-storage
        pip install mysql-connector-python
    - uses: stefanzweifel/git-auto-commit-action@v4
  gcp:
    runs-on: ubuntu-latest
    permissions:
      contents: 'read'
      id-token: 'write'

    steps:
    - uses: 'actions/checkout@v3'

    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v0'
      with:
        workload_identity_provider: 'projects/123456789/locations/global/workloadIdentityPools/my-pool/providers/my-provider'
        service_account: 'teste-254@dataops-383600.iam.gserviceaccount.com'

    - uses: wagnerpereira/gce-cloudsql-proxy-action@v2
      with:
        instance: my-project:us-central1:instance-1
        
    - name: execute py script
      run: python scraping_script.py
